# Generated by Django 4.2.1 on 2023-06-01 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_category_movie_cat"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["id"],
                "verbose_name": "Категорія",
                "verbose_name_plural": "Категорії",
            },
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={
                "ordering": ["time_create", "title"],
                "verbose_name": "Кращі кінофільми",
                "verbose_name_plural": "Кращі кінофільми",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="Категорія"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="cat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="movies.category",
                verbose_name="Категорія",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="content",
            field=models.TextField(blank=True, verbose_name="Текст статті"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубліковано"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="photo",
            field=models.ImageField(upload_to="photos/%Y/%m/%d/", verbose_name="Фото"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="time_create",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Час створення"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="time_update",
            field=models.DateTimeField(auto_now=True, verbose_name="Час зміни"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Заголовок"),
        ),
    ]
