# Generated by Django 4.2.1 on 2023-06-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_category_options_alter_movie_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=255, null=True, verbose_name="URL"),
        ),
        migrations.AddField(
            model_name="movie",
            name="slug",
            field=models.SlugField(max_length=255, null=True, verbose_name="URL"),
        ),
    ]
